const data = {
  cardData: [
    {
      id: 1,
      img: "",
      name: "machine Learining",
      desc: "this is description of ml",
      link: "./ContentPage",
      img: "https://th.bing.com/th/id/OIP.IhGijgoVTEs0_4rPuUXboQHaE8?w=216&h=180&c=7&r=0&o=5&dpr=1.2&pid=1.7",
    },
    {
      id: 2,
      img: "",
      name: "dsa",
      desc: "this is description of dsa",
      link: "./ContentPage",
      img: "https://th.bing.com/th/id/OIP.IhGijgoVTEs0_4rPuUXboQHaE8?w=216&h=180&c=7&r=0&o=5&dpr=1.2&pid=1.7",
    },
    {
      id: 3,
      img: "",
      name: "cns",
      desc: "this is description of cns",
      link: "./ContentPage",
      img: "https://th.bing.com/th/id/OIP.IhGijgoVTEs0_4rPuUXboQHaE8?w=216&h=180&c=7&r=0&o=5&dpr=1.2&pid=1.7",
    },
    {
      id: 4,
      img: "",
      name: "system design",
      desc: "this is description of sys",
      link: "./ContentPage",
      img: "https://th.bing.com/th/id/OIP.IhGijgoVTEs0_4rPuUXboQHaE8?w=216&h=180&c=7&r=0&o=5&dpr=1.2&pid=1.7",
    },
    {
      id: 5,
      img: "",
      name: "machine Learining",
      desc: "this is description of ml",
      link: "./ContentPage",
      img: "https://th.bing.com/th/id/OIP.IhGijgoVTEs0_4rPuUXboQHaE8?w=216&h=180&c=7&r=0&o=5&dpr=1.2&pid=1.7",
    },
    {
      id: 6,
      img: "",
      name: "dsa",
      desc: "this is description of dsa",
      link: "./ContentPage",
      img: "https://th.bing.com/th/id/OIP.IhGijgoVTEs0_4rPuUXboQHaE8?w=216&h=180&c=7&r=0&o=5&dpr=1.2&pid=1.7",
    },
    {
      id: 7,
      img: "",
      name: "cns",
      desc: "this is description of cns",
      link: "./ContentPage",
      img: "https://th.bing.com/th/id/OIP.IhGijgoVTEs0_4rPuUXboQHaE8?w=216&h=180&c=7&r=0&o=5&dpr=1.2&pid=1.7",
    },
    {
      id: 8,
      img: "",
      name: "system design",
      desc: "this is description of sys",
      link: "./ContentPage",
    },
  ],
};
export default data;
